on:
  push:
      branches:
        - newmaster  
    





jobs:
  build:
      runs-on: windows-latest 
      
      steps:
        - name: 'test'
          run: pwd
        - name: 'ahmedd'
          run: echo ahmed  

